### PR TITLE
Docker and Continuous Integration

### PR DESCRIPTION
**Pull request by bjfultn**
- added a Dockerfile to build a pristine environment for testing
- added makefile for convenience
- added .travis.yml for continuous integration with Travis CI

### CODE REVIEW

**Comment by bjfultn** [comment]
@shbhuk this will take some final tweaks to transition what I've set up for my fork over to this repo.

**Comment by bjfultn** [comment]
1. Merge into your `dev` or another branch specific to this feature.
1. Install docker desktop on your machine and run the tests locally with `make docker_tests` to make sure everything is working
2. Head over to travis-ci.com and try to add your repo. It should send you back to GitHub to enable access for Travis CI
3. Go to coveralls.io, sign in with GitHub credentials and add your repo there as well. Grab the repo token and insert it into the COVERALLS_REPO_TOKEN variable in the Dockerfile
3. Once Travis is allowed access, try to manually trigger a build and see that it runs to completion
4. Change the badges to point to this repo instead of my fork by replacing bjfultn --> shbhuk in README.md

**Comment by bjfultn** [comment]
You can also set this up so that it automatically pushes to pipy if it detects a new commit to master, or a new tag, or however you want to set it up. See the `deploy` section of the .travis.yml file in [https://github.com/California-Planet-Search/radvel](url) for an example of pushing when a new tag is detected.

**Comment by shbhuk** [comment]
This is really cool, thank you!! I'll take a look and modify it.

**Comment by shbhuk** [comment]
I was having some issue getting docker started, but for now I've at least integrated Travis CI, will then add coveralls.
Thanks for suggesting and showing this!

**Pull request merged**
